### PR TITLE
fix Japanese translation

### PR DESCRIPTION
**Pull request by lovetwice1012**
Fixed Japanese translation of readme.md and intl_ja.arb

### CODE REVIEW

**Comment by lovetwice1012** [comment]
SUPPLEMENTARY :
English letters can be used for proper nouns in Japanese.
The word "艦橋" was specified as an appname, but since the word is used as a noun in Japanese, we decided that an English name would be more appropriate.
Therefore, we have changed appname, etc. to English letters, but if you do not want this change, you can revert back to the original.

**Comment by andychucs** [comment]
ありがとう。

The appname is not used. The displayname of the application is actually placed in the ios and android directories, and I will modify the specific changes.

I still have questions about appname. Is the alphabet appname more acceptable for Japanese native speakers?

This project was originally based on the theme of the bridge(艦橋), so I chose the name in jp and zh, and because the bridge as the name of the project is not unique enough, appname use conning tower in en.

So which of the following names is more friendly to native speakers? 
1. 艦橋
2. ConningTower
3. Bridge


And 『HTTPリダイレクト』has been modified to 『HTTP転送』 because it is too long.
Does this modification conform to the habits of native speakers ?

There are also problems with other buttons that are too long. Do you have any better suggestions?

**Review by andychucs — APPROVED** [review]

**Comment by lovetwice1012** [comment]
I think conning tower would be more fitting than 艦橋.
Bridge would also be fine, but most Japanese would imagine it as a bridge over a river.
many Japanese may not be familiar with the word "リダイレクト". However, if it is called "転送," it is even more difficult to understand.
Ideally, the APP should obtain the iOS version and automatically execute a script when necessary, but if this is difficult, an "iOS15対策" would be preferable.

**Comment by andychucs** [comment]
What about HTTPﾘﾀﾞｲﾚｸﾄ？

Actually, all OS in the current version run http redirect and full screen by default, so ”iOS15対策“ is not fitting. Because it will use not often , this function is later planned to be placed in the secondary menu and maybe only used on iOS15+. At that time, it may be more fitting to change it to ”iOS15対策“.

**Comment by lovetwice1012** [comment]
I see.
Regarding HTTPリダイレクト, I thought some people might not be familiar with the term "リダイレクト"!
However, I think we can avoid this problem by guiding them in what situations they should press the button.
As for the character limit, how about putting a line break between the words "HTTP" and "リダイレクト" like in the case of an HTTP\n リダイレクト?

**Comment by lovetwice1012** [comment]
I forgot to mention the notation "ﾘﾀﾞｲﾚｸﾄ".
Half-width katakana is not only rarely used in Japan, it is almost always banned in business!
It is often used for joking around, which is very likely to cause discomfort to the other party.

**Comment by andychucs** [comment]
I see 
I will try line break
Try half width just because this 😂image

**Pull request merged**
